#!/bin/bash
#
# Captures a REFERENCE sample of real tilt output, to read log shapes out of.
#
#   docs/testing/capture-log-corpus.sh [port] [tail-count] [output-path] [target-size]
#
#   docs/testing/capture-log-corpus.sh 10350 30000 /tmp/log-shapes.jsonl 3500
#
# ## Its output is NOT the test fixture, and must never be committed
#
# `Tests/FulcrumKitTests/Fixtures/log-corpus.jsonl` is GENERATED, by
# docs/testing/generate-log-corpus.swift. It used to be the raw output of this
# script, and that was a mistake for a repository that is public: the file
# carried no credentials, but it did carry one company's internal hostnames,
# service names, tenant slugs, live record ids, API route shapes and database
# table names, and public git history is permanent.
#
# This script is kept anyway, because it is the only honest way to learn what a
# real emitter's output actually looks like. Every shape in the generator was
# read off a capture like this one -- the exact ANSI byte layout pino-pretty
# writes, the two-space gap postgres puts after `ERROR:`, the fact that tilt
# stamps every record with the time of the DUMP rather than of the line, the
# fact that `[Docker Prune]` lines carry an empty `resource` AND `spanID`. None
# of that is guessable, and a contributor adding a NEW shape to the generator
# should capture it rather than invent it.
#
# So the workflow is: run this against YOUR OWN tilt instance, READ the output,
# then teach `generate-log-corpus.swift` the shape you found and regenerate.
# The default output path below is a temp file for exactly that reason. Nothing
# under Fixtures/ should ever be this script's output again.
#
# READ-ONLY. This only ever runs `tilt logs --json`, which replays tilt's own
# log buffer to stdout -- it never triggers, enables, disables, or brings a
# resource down. Safe to point at a real, running project.
#
# What "trim" means here: in a raw capture the overwhelming majority of lines
# are ordinary traffic, and the interesting ones are rare and scattered rather
# than clustered -- so a naive head/tail slice would likely cut the very lines
# the severity rules exist to validate against. Instead every line carrying a
# known severity signal is kept unconditionally, and the remaining ordinary
# lines are downsampled at a fixed stride (preserving chronological order) to
# bring the file down to a "few thousand lines" corpus that still has enough
# non-error traffic to make false positives visible.
#
# Signals kept unconditionally:
#   - a literal ERROR or FATAL token in the message
#   - an ANSI red SGR code (\u001b[31 or \u001b[91) anywhere in the line --
#     tilt's --json output escapes ESC as \u001b rather than a raw 0x1B byte,
#     so that is what later rules (and this script) must match against
#   - a pino-style JSON message with "level":50
#   - a pino-style JSON message with a "statusCode" in 500-599
#   - a pino-style JSON message with an "err": {...} object
#   - a stack-frame line ("    at ...") inside a message
#
# This script also redacts JWT-shaped values (eyJ... base64url segments,
# whether embedded in a query string or an "Authorization: Bearer ..." log
# line) in place, since those are structurally credential material regardless
# of which environment emitted them. Live vite `http proxy error:` lines carry
# real JWTs in the query string, and those lines are exactly the ones the
# severity feature tints and jumps to -- so this redaction is load-bearing even
# for a file you only intend to read on your own machine.
#
# It is a mechanical safety net only. The old advice here was "grep before
# committing"; the advice now is DO NOT COMMIT THIS AT ALL. Redaction cannot
# find a hostname, a service name or a table name, and those are what made the
# previous fixture a disclosure.
set -euo pipefail

fail() { printf '\n\033[31mFAILED: %s\033[0m\n' "$1" >&2; exit 1; }
say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

PORT="${1:-10350}"
TILT_TAIL="${2:-30000}"
# A temp file, deliberately. Pointing this at Fixtures/ would overwrite a
# generated file with a captured one and re-introduce the disclosure this
# whole arrangement exists to remove.
OUT="${3:-/tmp/log-shapes.jsonl}"
TARGET_SIZE="${4:-3500}"

# Checked BEFORE anything is captured: a guard that fires after the write has
# already destroyed the file it was guarding.
case "$OUT" in
  *Tests/FulcrumKitTests/Fixtures/*)
    fail "refusing to leave a capture under Fixtures/ -- that file is generated by docs/testing/generate-log-corpus.swift"
    ;;
esac

command -v tilt >/dev/null 2>&1 || fail "tilt not found on PATH"
command -v python3 >/dev/null 2>&1 || fail "python3 not found on PATH"

# The name mktemp returns, unmodified. Appending ".jsonl" to it -- as this
# did -- renames the file the script writes but NOT the empty one mktemp
# already created, so every run left a stray /var/folders/.../log-corpus-raw.*
# behind that the trap never saw. Verified: after the trap ran, the mktemp file
# was still there. Nothing here reads the temp file by extension.
RAW="$(mktemp -t log-corpus-raw)"
trap 'rm -f "$RAW"' EXIT

say "Reading the last $TILT_TAIL lines from tilt --port $PORT (read-only, no --follow)"
tilt logs --port "$PORT" --json --tail "$TILT_TAIL" > "$RAW"

CAPTURED=$(wc -l < "$RAW" | tr -d ' ')
[ "$CAPTURED" -gt 0 ] || fail "captured zero lines -- is tilt running on port $PORT?"
say "Captured $CAPTURED raw lines"

say "Trimming to ~$TARGET_SIZE lines, keeping every signal-bearing line, and redacting JWT-shaped values"
python3 - "$RAW" "$OUT" "$TARGET_SIZE" <<'PY'
import json
import re
import sys

raw_path, out_path, target_size = sys.argv[1], sys.argv[2], int(sys.argv[3])

ERROR_RE = re.compile(r'\b(ERROR|FATAL)\b')
RED_RE = re.compile(r'\\u001b\[[0-9;]*(31|91)m')
STACK_RE = re.compile(r'^\s*at\s+\S')
ERR_BLOCK_RE = re.compile(r'\berr:\s*\{')
JWT_RE = re.compile(r'eyJ[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)+(?:\.\.\.)?')


def is_signal(raw_line: str, obj: dict) -> bool:
    message = obj.get("message", "")
    if ERROR_RE.search(message):
        return True
    if RED_RE.search(raw_line):
        return True
    stripped = message.strip()
    if stripped.startswith("{"):
        try:
            inner = json.loads(stripped)
        except ValueError:
            inner = None
        if isinstance(inner, dict):
            if inner.get("level") == 50:
                return True
            status_code = inner.get("statusCode")
            if isinstance(status_code, int) and 500 <= status_code <= 599:
                return True
            if isinstance(inner.get("err"), dict):
                return True
    if ERR_BLOCK_RE.search(message):
        return True
    for line in message.split("\n"):
        if STACK_RE.match(line):
            return True
    return False


with open(raw_path, "r", encoding="utf-8") as f:
    lines = [line.rstrip("\n") for line in f if line.strip()]

flags = []
for line in lines:
    obj = json.loads(line)
    flags.append(is_signal(line, obj))

signal_idx = [i for i, flag in enumerate(flags) if flag]
ordinary_idx = [i for i, flag in enumerate(flags) if not flag]

budget = max(target_size - len(signal_idx), 0)
stride = max(len(ordinary_idx) // budget, 1) if budget else len(ordinary_idx) + 1
sampled_ordinary_idx = ordinary_idx[::stride]

keep_idx = sorted(set(signal_idx) | set(sampled_ordinary_idx))

redacted = 0
out_lines = []
for i in keep_idx:
    new_line, n = JWT_RE.subn("<REDACTED-JWT>", lines[i])
    redacted += n
    out_lines.append(new_line)

with open(out_path, "w", encoding="utf-8") as out:
    for line in out_lines:
        out.write(line + "\n")

print(
    f"kept {len(out_lines)} lines ({len(signal_idx)} signal-bearing, "
    f"{len(sampled_ordinary_idx)} ordinary of {len(ordinary_idx)}), "
    f"redacted {redacted} JWT-shaped value(s)"
)
PY

FINAL=$(wc -l < "$OUT" | tr -d ' ')
say "Wrote $FINAL lines to $OUT"

say "This is a REFERENCE capture. Read it; do not commit it."
cat <<EOF
  It still contains your project's hostnames, service names, tenant slugs,
  record ids, route shapes and table names. Redaction above only covers
  credential-shaped values.

  Next step: teach docs/testing/generate-log-corpus.swift the shape you came
  here for, then re-run it and re-derive the counts pinned in
  LogCorpusTests.swift and SeverityScannerTests.swift.

  A credential sweep over the capture, if you are keeping it around:
  grep -inE 'password|secret|bearer|authorization|api[_-]?key|AKIA[0-9A-Z]{16}|-----BEGIN|[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}|eyJ[A-Za-z0-9_-]{10,}' "$OUT"
EOF
